"""create analysis findings table

Revision ID: 3a36a45d6a53
Revises: 18bd02f50885
Create Date: 2026-09-10 10:32:13.031031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a36a45d6a53'
down_revision: Union[str, Sequence[str], None] = '18bd02f50885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('column', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['code_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_findings')
    # ### end Alembic commands ###
